import { z } from 'zod';

export const SolvedElementSchema = z.object({
  id: z.string(),
  kind: z.enum(['text', 'shape', 'connector', 'group', 'media', 'icon', 'chart_axis', 'chart_mark', 'chart_label', 'annotation', 'region']),
  semanticRole: z.string(),
  importance: z.enum(['primary', 'secondary', 'supporting', 'structural']),
  x: z.number(),
  y: z.number(),
  width: z.number().nonnegative(),
  height: z.number().nonnegative(),
  zIndex: z.number().int(),
  content: z.union([z.string(), z.record(z.string(), z.unknown())]).nullable(),
  intrinsic: z.object({ width: z.number().nonnegative().optional(), height: z.number().nonnegative().optional() }).strict(),
  constraints: z.object({
    minWidth: z.number().nonnegative().optional(), maxWidth: z.number().positive().optional(),
    minHeight: z.number().nonnegative().optional(), maxHeight: z.number().positive().optional(),
    maxLines: z.number().int().positive().optional(), parentId: z.string().nullable().optional(),
    protected: z.boolean(),
  }).strict(),
  styleTokenRefs: z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])),
  parentId: z.string().nullable(),
  anchors: z.record(z.string(), z.object({ x: z.number(), y: z.number() })).optional(),
  semanticBinding: z.object({ type: z.string(), value: z.string(), phraseId: z.string().nullable().optional() }).strict().nullable().default(null),
  textVariants: z.object({ full: z.string(), short: z.string(), labelOnly: z.string() }).strict().optional(),
  visualHierarchy: z.object({
    tier: z.enum(['PRIMARY', 'SECONDARY', 'SUPPORTING', 'DECORATIVE']),
    visualWeight: z.number().min(0).max(1),
    reasons: z.array(z.string()),
  }).strict(),
}).strict();

export const TextLayoutSchema = z.object({
  elementId: z.string(),
  fontFamily: z.string(),
  fontWeight: z.number(),
  fontSize: z.number().positive(),
  lineHeight: z.number().positive(),
  lineBreaks: z.array(z.string()),
  boxWidth: z.number().positive(),
  boxHeight: z.number().positive(),
  measuredWidth: z.number().nonnegative(),
  measuredHeight: z.number().nonnegative(),
  metricsSource: z.string(),
  constraintUnsatisfied: z.boolean(),
  fitStatus: z.enum(['FIT', 'FIT_WITH_WRAP', 'FIT_WITH_REWRITE_REQUIRED', 'FAILED']),
  reductionTier: z.enum(['FULL', 'SHORT', 'LABEL_ONLY']),
}).strict();

export const ConnectorRouteSchema = z.object({
  id: z.string(),
  from: z.string(),
  to: z.string(),
  type: z.enum(['straight', 'elbow', 'curved']),
  points: z.array(z.object({ x: z.number(), y: z.number() })).min(2),
  pathData: z.string(),
  startAnchor: z.string(),
  endAnchor: z.string(),
}).strict();

export const SolvedSceneSchema = z.object({
  version: z.literal(1),
  id: z.string(),
  shotId: z.string(),
  format: z.enum(['landscape', 'shorts']),
  viewport: z.object({ width: z.number().positive(), height: z.number().positive() }).strict(),
  topology: z.enum([
    'horizontal', 'vertical', 'two-row',
    'dual-field', 'shared-baseline', 'spectrum', 'before-after', 'two-column-editorial', 'stacked-vertical', 'delta-comparison',
    'bar-vertical', 'bar-horizontal', 'line', 'area', 'dot', 'progress', 'simple-stack',
    'full-bleed-media', 'editorial-split-media', 'media-dominant-split', 'detail-focus-media', 'image-plus-stat', 'image-plus-callout', 'evidence-frame-media', 'two-media-compare', 'layered-media', 'background-media', 'montage-media',
  ]),
  elements: z.record(z.string(), SolvedElementSchema),
  connectorRoutes: z.array(ConnectorRouteSchema),
  textLayout: z.record(z.string(), TextLayoutSchema),
  occupancy: z.object({ ratio: z.number().min(0), bounds: z.object({ x: z.number(), y: z.number(), width: z.number(), height: z.number() }).strict() }).strict(),
  constraintsSatisfied: z.boolean(),
  warnings: z.array(z.string()),
  constraintUnsatisfied: z.array(z.object({ elementId: z.string(), constraint: z.string(), detail: z.string() }).strict()),
  repairHistory: z.array(z.object({ pass: z.number().int(), action: z.string(), reason: z.string() }).strict()),
  regions: z.record(z.string(), z.object({ x: z.number(), y: z.number(), width: z.number(), height: z.number() }).strict()),
  chartCoordinateSystem: z.object({
    plot: z.object({ x: z.number(), y: z.number(), width: z.number().positive(), height: z.number().positive() }).strict(),
    x: z.object({ scaleType: z.enum(['linear', 'categorical']), domain: z.array(z.union([z.string(), z.number()])), range: z.tuple([z.number(), z.number()]), ticks: z.array(z.object({ value: z.union([z.string(), z.number()]), position: z.number(), label: z.string() }).strict()), baseline: z.number() }).strict(),
    y: z.object({ scaleType: z.enum(['linear', 'categorical']), domain: z.array(z.union([z.string(), z.number()])), range: z.tuple([z.number(), z.number()]), ticks: z.array(z.object({ value: z.union([z.string(), z.number()]), position: z.number(), label: z.string() }).strict()), baseline: z.number() }).strict(),
  }).strict().nullable(),
  annotationGeometry: z.record(z.string(), z.object({ x: z.number(), y: z.number(), width: z.number().nonnegative(), height: z.number().nonnegative(), targetX: z.number(), targetY: z.number() }).strict()),
  captionBox: z.object({ x: z.number(), y: z.number(), width: z.number().positive(), height: z.number().nonnegative() }).strict(),
  backgroundSelection: z.enum(['neutralDark', 'charcoal', 'paperLight', 'softRadial', 'subtleTexture', 'technicalGrid']),
  formatPolicy: z.object({ orientation: z.enum(['landscape', 'vertical']), interactionSafeApplied: z.boolean(), maximumConcepts: z.number().int().positive(), maximumTicks: z.number().int().nonnegative() }).strict(),
  complexity: z.object({ level: z.enum(['LOW', 'MEDIUM', 'HIGH']), mainTargets: z.number().int(), supportElements: z.number().int(), relationships: z.number().int(), withinBudget: z.boolean() }).strict(),
  mediaGeometry: z.record(z.string(), z.object({
    assetId: z.string(), src: z.string(), mediaType: z.enum(['image', 'video']),
    rect: z.object({ x: z.number(), y: z.number(), width: z.number().nonnegative(), height: z.number().nonnegative() }).strict(),
    crop: z.object({ x: z.number().min(0).max(1), y: z.number().min(0).max(1), width: z.number().min(0).max(1), height: z.number().min(0).max(1) }).strict(),
    objectPosition: z.object({ x: z.number().min(0).max(1), y: z.number().min(0).max(1) }).strict(),
    scale: z.number().positive(), transformOrigin: z.string(), subjectSafeRegion: z.object({ x: z.number(), y: z.number(), width: z.number().nonnegative(), height: z.number().nonnegative() }).strict().nullable(),
    treatment: z.object({ scrim: z.enum(['none', 'subtle-gradient', 'local-shade', 'localized-blur']), brightness: z.number(), contrast: z.number(), tintOpacity: z.number(), vignette: z.number() }).strict(),
    sourceDimensions: z.object({ width: z.number().positive().nullable(), height: z.number().positive().nullable() }).strict(),
    nativeMotion: z.boolean(), activeRange: z.object({ startFrame: z.number().int().nonnegative(), endFrame: z.number().int().nonnegative() }).strict().nullable(),
  }).strict()).default({}),
  cameraPaths: z.record(z.string(), z.object({
    behavior: z.enum(['STATIC', 'SUBTLE_PUSH', 'SUBTLE_PULL', 'FOCAL_PAN', 'DETAIL_CROP', 'REFRAME', 'MATCH_MOVE']),
    start: z.object({ scale: z.number().positive(), focusX: z.number().min(0).max(1), focusY: z.number().min(0).max(1) }).strict(),
    end: z.object({ scale: z.number().positive(), focusX: z.number().min(0).max(1), focusY: z.number().min(0).max(1) }).strict(),
    rationale: z.string(),
  }).strict()).default({}),
}).strict();
